### ISSUE TITLE
[Documentation] Add Documentation for Installing with HACS and Manually

### ISSUE THREAD

**Issue by LudusLight** [alanjames1987/Wyze-HA#1]
Add documentation on how to install / use integration with and without HACS

**Comment by alanjames1987** [comment]
I'll add this at some point but that is already documented on HACS itself.

https://hacs.xyz/docs/faq/custom_repositories/

**Comment by alanjames1987** [comment]
Additionally, you are welcome to make the changes to the `README.md` file and submit a pull request. I'm more than willing to accept it.

**Comment by alanjames1987** [comment]
The first pass of this has beed added.
