### ISSUE TITLE
[Bug] Vac breaks Google Integration and ability to restart from Core

### ISSUE THREAD

**Issue by codypet** [alanjames1987/Wyze-HA#11]
Configuration validation just spools and I can't restart after installing application and setting up the config file.

I'm running core-2021.9.6

When I tried a hard restart of HA my google devices disconnected. They reappeared after I deleted the integration. The vacuum entities never showed up.  Happens with both Wyze Vac integrations [This one too](https://github.com/romedtino/simple-wyze-vac)

This is the error I get in my for my nest and when I restart.
https://hastebin.com/efasulezeq

**Comment by alanjames1987** [comment]
Hey @codypet are you using 2FA on your Wyze account?

**Comment by codypet** [comment]
Nope, I'm not using 2FA

**Comment by alanjames1987** [comment]
That's a very strange error. I've never had that type of error occur.

I'm also running core-2021.9.6 but the only Nest devices I have are Next Mini's so I don't know if I can trigger conflicts. Conceptually one integration shouldn't affect other integrations.

I doubt it will help me track it down but what Nest devices do you have that aren't appearing? That will give a direction but probably won't give many answers.

**Comment by codypet** [comment]
I have a 2nd gen Nest thermostat.  That's the only Nest product I have.  

The weird thing that threw me was getting that same error whenever I hit "restart" in homeassistant.  I don't know why it'd give me that error then and why it would prevent me from restarting.

**Comment by alanjames1987** [comment]
Thanks for linking to that. It gave me an idea that a lower lower lower library might be on the wrong version.

You can check out my comment here and see if that fixes the problem. If it does I think I might be able to request a later version of Protobuf be installed in my integration and have it work well.

**Comment by codypet** [comment]
That protobuf update to 3.13 did the trick.  You are a gentleman and a scholar.  If you ever want to hit up Sideward or Ivanhoe, I'll cover a pint.
