### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by LudusLight** [alanjames1987/Wyze-HA#2]
Add function to map the floor without cleaning

**Comment by alanjames1987** [comment]
This functionality isn't supported by[ Wyze-SDK](https://github.com/shauntarves/wyze-sdk) which this integration is a wrapper for.

Additionally, [Home Assistant itself doesn't support the feature](https://www.home-assistant.io/integrations/vacuum/) to trigger to map a floor without vacuuming. The services it supports are  `turn_on`, `turn_off`, `start_pause`, `start`, `pause`, `stop`, `return_to_base`, `locate`, `clean_spot`, `set_fanspeed` and `send_command`.

Most are easy to understand and `send_command` is for vacuums with the [Valetudo](https://valetudo.cloud/) firmware to run Linux commands.

Unfortunately this can't be added unless both Home Assistant and Wyze-SDK support this, in the order.
